package com.btl.transport.room;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;
import java.util.Optional;

public interface RoomAssignmentRepository extends JpaRepository<RoomAssignment, Integer> {

    @Query("SELECT ra FROM RoomAssignment ra LEFT JOIN FETCH ra.occupants o LEFT JOIN FETCH o.participant WHERE ra.programId = :programId ORDER BY ra.hotelName, ra.roomLabel")
    List<RoomAssignment> findByProgramIdWithOccupants(@Param("programId") String programId);

    /**
     * Composite key lookup for smart-merge CSV import.
     * Native query with CAST(:gender AS TEXT) to avoid PostgreSQL type-inference error
     * on bare "? IS NULL" parameters generated by JPQL.
     */
    @Query(value = """
        SELECT * FROM room_assignments
        WHERE program_id = :programId
          AND LOWER(hotel_name) = LOWER(:hotelName)
          AND LOWER(room_label) = LOWER(:roomLabel)
          AND (
            (gender IS NULL AND CAST(:gender AS TEXT) IS NULL)
            OR LOWER(gender) = LOWER(CAST(:gender AS TEXT))
          )
        """, nativeQuery = true)
    Optional<RoomAssignment> findByCompositeKey(
        @Param("programId") String programId,
        @Param("hotelName") String hotelName,
        @Param("roomLabel") String roomLabel,
        @Param("gender") String gender
    );

    List<RoomAssignment> findByProgramId(String programId);

    @Query("SELECT ra FROM RoomAssignment ra LEFT JOIN FETCH ra.occupants o LEFT JOIN FETCH o.participant WHERE ra.id = :id")
    Optional<RoomAssignment> findByIdWithOccupants(@Param("id") Integer id);
}
