name: Terraform Apply

on:
  workflow_dispatch:

env:
  TF_DIR: infra

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.7"

      - run: terraform init
      - run: terraform apply -auto-approve

      - name: Show outputs
        run: terraform output
